export const carSchemas = {
    createCar: {
        name: { type: 'string', required: true, minLength: 1 },
        brand: { type: 'string', required: true, minLength: 1 },
        model: { type: 'string', required: true, minLength: 1 },
        year: { type: 'number', required: true, min: 1900, max: 2100 },
        color: { type: 'string', required: true, minLength: 1 },
        price: { type: 'number', required: true, min: 0 },
        mileage: { type: 'number', required: false, min: 0 },
        description: { type: 'string', required: false },
        fuel_type: { type: 'string', required: false },
        transmission: { type: 'string', required: false },
        status: { type: 'string', required: false, enum: ['available', 'sold', 'reserved'] },
        images: { type: 'array', required: false, itemsType: 'string' },
    },
    updateCar: {
        name: { type: 'string', required: false, minLength: 1 },
        brand: { type: 'string', required: false, minLength: 1 },
        model: { type: 'string', required: false, minLength: 1 },
        year: { type: 'number', required: false, min: 1900, max: 2100 },
        color: { type: 'string', required: false, minLength: 1 },
        price: { type: 'number', required: false, min: 0 },
        mileage: { type: 'number', required: false, min: 0 },
        description: { type: 'string', required: false },
        fuel_type: { type: 'string', required: false },
        transmission: { type: 'string', required: false },
        status: { type: 'string', required: false, enum: ['available', 'sold', 'reserved'] },
        images: { type: 'array', required: false, itemsType: 'string' },
    },
    getCarById: {
        id: { type: 'string', required: true },
    },
}
