export const carSchemas = {
    createCar: {
        tenXe: { type: 'string', required: true, minLength: 1 },
        giaBan: { type: 'number', required: true, min: 0 },
        namSanXuat: { type: 'number', required: true, min: 1900, max: 2100 },
        mauSac: { type: 'string', required: true, minLength: 1 },
        soKhung: { type: 'string', required: true, minLength: 1 },
        soMay: { type: 'string', required: true, minLength: 1 },
        dungTich: { type: 'string', required: false },
        soLuongTon: { type: 'number', required: true, min: 0 },
        trangThai: { type: 'boolean', required: true },
        maHang: { type: 'number', required: true, min: 1 },
        maLoaiXe: { type: 'number', required: true, min: 1 },
    },
    updateCar: {
        tenXe: { type: 'string', required: false, minLength: 1 },
        giaBan: { type: 'number', required: false, min: 0 },
        namSanXuat: { type: 'number', required: false, min: 1900, max: 2100 },
        mauSac: { type: 'string', required: false, minLength: 1 },
        soKhung: { type: 'string', required: false, minLength: 1 },
        soMay: { type: 'string', required: false, minLength: 1 },
        dungTich: { type: 'string', required: false },
        soLuongTon: { type: 'number', required: false, min: 0 },
        trangThai: { type: 'boolean', required: false },
        maHang: { type: 'number', required: false, min: 1 },
        maLoaiXe: { type: 'number', required: false, min: 1 },
    },
}
